# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class NbaItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    isPlayer = scrapy.Field()
    value0 = scrapy.Field()
    value1 = scrapy.Field()
    value2 = scrapy.Field()
    value3 = scrapy.Field()
    value4 = scrapy.Field()
    value5 = scrapy.Field()
    value6 = scrapy.Field()
    value7 = scrapy.Field()
    value8 = scrapy.Field()
    value9 = scrapy.Field()
    value10 = scrapy.Field()
    value11 = scrapy.Field()
    value12 = scrapy.Field()
    value13 = scrapy.Field()
    value14 = scrapy.Field()
    value15 = scrapy.Field()
    value16 = scrapy.Field()
    value17 = scrapy.Field()
    value18 = scrapy.Field()
    value19 = scrapy.Field()
    value20 = scrapy.Field()
    value21 = scrapy.Field()
    value22 = scrapy.Field()
    value23 = scrapy.Field()
    value24 = scrapy.Field()
    value25 = scrapy.Field()
    value26 = scrapy.Field()
    value27 = scrapy.Field()
    value28 = scrapy.Field()
    value29 = scrapy.Field()
    value30 = scrapy.Field()
    value31 = scrapy.Field()
    value32 = scrapy.Field()
    value33 = scrapy.Field()
    value34 = scrapy.Field()
    value35 = scrapy.Field()
    value36 = scrapy.Field()
    value37 = scrapy.Field()
    value38 = scrapy.Field()
    value39 = scrapy.Field()
    value40 = scrapy.Field()
    value41 = scrapy.Field()
    value42 = scrapy.Field()
    value43 = scrapy.Field()
    value44 = scrapy.Field()
    value45 = scrapy.Field()
    value46 = scrapy.Field()
    value47 = scrapy.Field()
    value48 = scrapy.Field()
    value49 = scrapy.Field()
    value50 = scrapy.Field()
    value51 = scrapy.Field()
    value52 = scrapy.Field()
    value53 = scrapy.Field()
    value54 = scrapy.Field()
    value55 = scrapy.Field()
    value56 = scrapy.Field()
    value57 = scrapy.Field()
    value58 = scrapy.Field()
    value59 = scrapy.Field()
    value60 = scrapy.Field()
    value61 = scrapy.Field()
    value62 = scrapy.Field()
    value63 = scrapy.Field()
    value64 = scrapy.Field()

    pass
