# -*- coding: utf-8 -*-
import scrapy
import json
from nba.items import NbaItem

class NbastatsSpider(scrapy.Spider):
    name = 'nbastats'
    allowed_domains = ['stats.nba.com']
    start_urls = ['http://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2017-18&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=']

    def parse(self, response):
        print('parse start')
        players = json.loads(response.body_as_unicode())
        print('getplayer')
        headers = json.loads(response.body_as_unicode())
        print('getheaders')
        hItem = headers['resultSets'][0]['headers']

        players = players['resultSets'][0]['rowSet']
        item = NbaItem()
        item['isPlayer'] = False
        item['value0'] = hItem[0]
        item['value1'] = hItem[1]
        item['value2'] = hItem[2]
        item['value3'] = hItem[3]
        item['value4'] = hItem[4]
        item['value5'] = hItem[5]
        item['value6'] = hItem[6]
        item['value7'] = hItem[7]
        item['value8'] = hItem[8]
        item['value9'] = hItem[9]
        item['value10'] = hItem[10]
        item['value11'] = hItem[11]
        item['value12'] = hItem[12]
        item['value13'] = hItem[13]
        item['value14'] = hItem[14]
        item['value15'] = hItem[15]
        item['value16'] = hItem[16]
        item['value17'] = hItem[17]
        item['value18'] = hItem[18]
        item['value19'] = hItem[19]
        item['value20'] = hItem[20]
        item['value21'] = hItem[21]
        item['value22'] = hItem[22]
        item['value23'] = hItem[23]
        item['value24'] = hItem[24]
        item['value25'] = hItem[25]
        item['value26'] = hItem[26]
        item['value27'] = hItem[27]
        item['value28'] = hItem[28]
        item['value29'] = hItem[29]
        item['value30'] = hItem[30]
        item['value31'] = hItem[31]
        item['value32'] = hItem[32]
        item['value33'] = hItem[33]
        item['value34'] = hItem[34]
        item['value35'] = hItem[35]
        item['value36'] = hItem[36]
        item['value37'] = hItem[37]
        item['value38'] = hItem[38]
        item['value39'] = hItem[39]
        item['value40'] = hItem[40]
        item['value41'] = hItem[41]
        item['value42'] = hItem[42]
        item['value43'] = hItem[43]
        item['value44'] = hItem[44]
        item['value45'] = hItem[45]
        item['value46'] = hItem[46]
        item['value47'] = hItem[47]
        item['value48'] = hItem[48]
        item['value49'] = hItem[49]
        item['value50'] = hItem[50]
        item['value51'] = hItem[51]
        item['value52'] = hItem[52]
        item['value53'] = hItem[53]
        item['value54'] = hItem[54]
        item['value55'] = hItem[55]
        item['value56'] = hItem[56]
        item['value57'] = hItem[57]
        item['value58'] = hItem[58]
        item['value59'] = hItem[59]
        item['value60'] = hItem[60]
        item['value61'] = hItem[61]
        item['value62'] = hItem[62]
        item['value63'] = hItem[63]
        item['value64'] = hItem[64]
        yield item

        for each_player in players:
            item2 = NbaItem()
            item2['isPlayer'] = True
            item2['value0'] = each_player[0]
            item2['value1'] = each_player[1]
            item2['value2'] = each_player[2]
            item2['value3'] = each_player[3]
            item2['value4'] = each_player[4]
            item2['value5'] = each_player[5]
            item2['value6'] = each_player[6]
            item2['value7'] = each_player[7]
            item2['value8'] = each_player[8]
            item2['value9'] = each_player[9]
            item2['value10'] = each_player[10]
            item2['value11'] = each_player[11]
            item2['value12'] = each_player[12]
            item2['value13'] = each_player[13]
            item2['value14'] = each_player[14]
            item2['value15'] = each_player[15]
            item2['value16'] = each_player[16]
            item2['value17'] = each_player[17]
            item2['value18'] = each_player[18]
            item2['value19'] = each_player[19]
            item2['value20'] = each_player[20]
            item2['value21'] = each_player[21]
            item2['value22'] = each_player[22]
            item2['value23'] = each_player[23]
            item2['value24'] = each_player[24]
            item2['value25'] = each_player[25]
            item2['value26'] = each_player[26]
            item2['value27'] = each_player[27]
            item2['value28'] = each_player[28]
            item2['value29'] = each_player[29]
            item2['value30'] = each_player[30]
            item2['value31'] = each_player[31]
            item2['value32'] = each_player[32]
            item2['value33'] = each_player[33]
            item2['value34'] = each_player[34]
            item2['value35'] = each_player[35]
            item2['value36'] = each_player[36]
            item2['value37'] = each_player[37]
            item2['value38'] = each_player[38]
            item2['value39'] = each_player[39]
            item2['value40'] = each_player[40]
            item2['value41'] = each_player[41]
            item2['value42'] = each_player[42]
            item2['value43'] = each_player[43]
            item2['value44'] = each_player[44]
            item2['value45'] = each_player[45]
            item2['value46'] = each_player[46]
            item2['value47'] = each_player[47]
            item2['value48'] = each_player[48]
            item2['value49'] = each_player[49]
            item2['value50'] = each_player[50]
            item2['value51'] = each_player[51]
            item2['value52'] = each_player[52]
            item2['value53'] = each_player[53]
            item2['value54'] = each_player[54]
            item2['value55'] = each_player[55]
            item2['value56'] = each_player[56]
            item2['value57'] = each_player[57]
            item2['value58'] = each_player[58]
            item2['value59'] = each_player[59]
            item2['value60'] = each_player[60]
            item2['value61'] = each_player[61]
            item2['value62'] = each_player[62]
            item2['value63'] = each_player[63]
            item2['value64'] = each_player[64]
            yield item2

        pass
